misc: check package name compatibility between package from url and the resulting record.
Looks as follows:
> mv ~/_libgcc_mutex-0.1.0-conda.tar.bz2
> cargo run -- ~/mamba-1.2.3-bla.tar.bz2
Error: failed to load repodata

Caused by:
    the package from url '_libgcc_mutex', doesn't have the same name as the match spec filename intents 'mamba'